.importobj "obj/lib.o"

.importobj "obj/mapWarpExtra.o"
.importobj "obj/mapContainer.o"
.importobj "obj/japes.o"
.importobj "obj/aztec.o"
.importobj "obj/factory.o"
.importobj "obj/galleon.o"
.importobj "obj/fungi.o"
.importobj "obj/caves.o"
.importobj "obj/castle.o"
.importobj "obj/helmandkrool.o"
.importobj "obj/isles.o"
.importobj "obj/othermaps.o"
.importobj "obj/mapwarp_list.o"

.importobj "obj/snag_watch.o"
.importobj "obj/timer.o"
.importobj "obj/timer_settings.o"
.importobj "obj/watchContainer.o"
.importobj "obj/savestate.o"
.importobj "obj/filestates.o"

.importobj "obj/flagsContainer.o"
.importobj "obj/kongs.o"
.importobj "obj/keysin.o"
.importobj "obj/keyshave.o"
.importobj "obj/levelintros.o"
.importobj "obj/leveltns.o"
.importobj "obj/levelbosses.o"
.importobj "obj/cutscenes.o"
.importobj "obj/modifiers.o"
.importobj "obj/ftt.o"
.importobj "obj/misc.o"
.importobj "obj/custom.o"
.importobj "obj/tbarrels.o"
.importobj "obj/flagMenu_list.o"

.importobj "obj/instantskew.o"
.importobj "obj/cancelcutscene.o"
.importobj "obj/gaincontrol.o"
.importobj "obj/corrupt.o"
.importobj "obj/gamemode.o"
.importobj "obj/transform.o"
.importobj "obj/endminigame.o"
.importobj "obj/phase.o"
.importobj "obj/moonkick.o"
.importobj "obj/sandstorm.o"
.importobj "obj/preventenemyspawning.o"
.importobj "obj/tagbarrelvoid.o"
.importobj "obj/visify.o"
.importobj "obj/autokillboss.o"
.importobj "obj/moveset_inventory.o"
.importobj "obj/cranky.o"
.importobj "obj/funky.o"
.importobj "obj/candy.o"
.importobj "obj/toggles.o"
.importobj "obj/snag.o"
.importobj "obj/cheatscontainer.o"

.importobj "obj/settings_storage.o"
.importobj "obj/alterkongcolors.o"
.importobj "obj/alterinputquadrant.o"
.importobj "obj/dpadlr.o"
.importobj "obj/dpadd.o"
.importobj "obj/vanilla_vars.o"
.importobj "obj/hack_vars.o"
.importobj "obj/settingscontainer.o"

.importobj "obj/input.o"
.importobj "obj/saveprompt.o"
.importobj "obj/positionloading.o"
.importobj "obj/frameadvance.o"
.importobj "obj/activeMenu.o"
.importobj "obj/aesthetic.o"
.importobj "obj/levitate.o"
.importobj "obj/tagAnywhere.o"
.importobj "obj/file_init.o"
.importobj "obj/init.o"

.importobj "obj/actor.o"
.importobj "obj/ramview.o"
.importobj "obj/debug.o"

.importobj "obj/main.o"