.importobj "obj/lib.o"

.importobj "obj/mapContainer.o"
.importobj "obj/japes.o"
.importobj "obj/aztec.o"
.importobj "obj/factory.o"
.importobj "obj/galleon.o"
.importobj "obj/fungi.o"
.importobj "obj/caves.o"
.importobj "obj/castle.o"
.importobj "obj/helmandkrool.o"
.importobj "obj/isles.o"
.importobj "obj/mapwarp_list.o"

.importobj "obj/timer.o"
.importobj "obj/timer_settings.o"
.importobj "obj/watchContainer.o"
.importobj "obj/savestate.o"
.importobj "obj/filestates.o"

.importobj "obj/flagsContainer.o"
.importobj "obj/kongs.o"
.importobj "obj/keysin.o"
.importobj "obj/keyshave.o"
.importobj "obj/levelintros.o"
.importobj "obj/leveltns.o"
.importobj "obj/levelbosses.o"
.importobj "obj/cutscenes.o"
.importobj "obj/modifiers.o"
.importobj "obj/ftt.o"
.importobj "obj/misc.o"
.importobj "obj/custom.o"
.importobj "obj/flagMenu_list.o"

.importobj "obj/instantskew.o"
.importobj "obj/cancelcutscene.o"
.importobj "obj/gaincontrol.o"
.importobj "obj/corrupt.o"
.importobj "obj/gamemode.o"
.importobj "obj/cheatscontainer.o"


.importobj "obj/settings_storage.o"
.importobj "obj/alterkongcolors.o"
.importobj "obj/settingscontainer.o"

.importobj "obj/saveprompt.o"
.importobj "obj/activeMenu.o"
.importobj "obj/aesthetic.o"
.importobj "obj/levitate.o"
.importobj "obj/tagAnywhere.o"
.importobj "obj/init.o"
.importobj "obj/ramview.o"
.importobj "obj/main.o"