/*
	This is an automatically generated file.
	Please don't make edits to this file directly as they will be overwritten at next build.
	To make amendments, see include/screens_list.json and build/screen_generator.py.
	Thanks.
*/

#include "vars.h"

extern const Screen main_struct;
extern const Screen maps_container_struct;
extern const Screen japes_mapwarp_struct;
extern const Screen japesmain_mapwarp_struct;
extern const Screen aztec_mapwarp_struct;
extern const Screen aztecmain_mapwarp_struct;
extern const Screen aztecfivedt_mapwarp_struct;
extern const Screen factory_mapwarp_struct;
extern const Screen factorymain_mapwarp_struct;
extern const Screen galleon_mapwarp_struct;
extern const Screen galleonmain_mapwarp_struct;
extern const Screen galleonships_mapwarp_struct;
extern const Screen watch_struct;
extern const Screen fungi_mapwarp_struct;
extern const Screen fungimain_mapwarp_struct;
extern const Screen fungigmush_mapwarp_struct;
extern const Screen fungimills_mapwarp_struct;
extern const Screen caves_mapwarp_struct;
extern const Screen cavesmain_mapwarp_struct;
extern const Screen caves5dc_mapwarp_struct;
extern const Screen caves5di_mapwarp_struct;
extern const Screen castle_mapwarp_struct;
extern const Screen castlemain_mapwarp_struct;
extern const Screen castlecrypt_mapwarp_struct;
extern const Screen castletunnel_mapwarp_struct;
extern const Screen castleoutside_mapwarp_struct;
extern const Screen castlerooms_mapwarp_struct;
extern const Screen isles_mapwarp_struct;
extern const Screen islesmain_mapwarp_struct;
extern const Screen isleslobbies_mapwarp_struct;
extern const Screen helmrool_mapwarp_struct;
extern const Screen state_struct;
extern const Screen changestate_struct;
extern const Screen timersettings_struct;
extern const Screen filestates_main_struct;
extern const Screen filestates_nle_struct;
extern const Screen filestates_101main_struct;
extern const Screen filestates_general_struct;
extern const Screen filestates_101org_struct;
extern const Screen filestates_101jfm_struct;
extern const Screen filestates_101ffm_struct;
extern const Screen viewstate_struct;
extern const Screen flagmain_struct;
extern const Screen flagmenu_kongs_struct;
extern const Screen flagmenu_keysin_struct;
extern const Screen flagmenu_keyshave_struct;
extern const Screen flagmenu_levelintros_struct;
extern const Screen flagmenu_leveltns_struct;
extern const Screen flagmenu_levelboss_struct;
extern const Screen flagmenu_cutscene_struct;
extern const Screen flagmenu_modifier_struct;
extern const Screen flagmenu_ftt_struct;
extern const Screen flagmenu_misc_struct;
extern const Screen flagcustom_struct;
extern const Screen cheats_struct;
extern const Screen gamemode_struct;
extern const Screen settings_struct;
extern const Screen kongcolors_struct;
extern const Screen quadrant_struct;
extern const Screen dpadlr_struct;
extern const Screen dpadd_struct;
extern const Screen transform_struct;
extern const Screen moveset_struct;
extern const Screen cranky_struct;
extern const Screen funky_struct;
extern const Screen candy_struct;
extern const Screen flagmenu_tbarrels_struct;
extern const Screen vanilla_struct;
extern const Screen hack_struct;
extern const Screen other_mapwarp_struct;
extern const Screen toggles_struct;
extern const Screen snagcheats_struct;
extern const Screen debug_struct;
extern Screen actor_struct;
extern const Screen detailsscreen_struct;
extern const Screen watch_player_struct;
extern const Screen watch_timers_struct;
extern const Screen watch_sysenv_struct;
extern Screen watch_snag_struct;
extern const Screen watch_assist_struct;
extern const Screen heap_struct;
extern Screen flaglog_struct;
extern const Screen instruction_struct;
extern const Screen testinfo_struct;
extern const Screen forcespawn_struct;
extern const Screen filestates_glitchless_struct;
extern const Screen bonusmain_mapwarp_struct;
extern const Screen bonusjapes_mapwarp_struct;
extern const Screen bonusaztec_mapwarp_struct;
extern const Screen bonusfactory_mapwarp_struct;
extern const Screen bonusgalleon_mapwarp_struct;
extern const Screen bonusfungi_mapwarp_struct;
extern const Screen bonuscaves_mapwarp_struct;
extern const Screen bonuscastle_mapwarp_struct;
extern const Screen bonushelm_mapwarp_struct;
extern const Screen bonusisles_mapwarp_struct;
extern const Screen collisionmenu_struct;
extern const Screen floormenu_struct;
extern const Screen bports_struct;
extern const Screen watch_fake_struct;
extern const Screen state_settings_struct;
extern const Screen tricktoggles_struct;
extern const Screen infinite_struct;
extern const Screen filestates_nlemain_struct;
extern const Screen filestates_nle40_struct;
extern const Screen fixes_struct;
extern const Screen memory_struct;
extern Screen freeze_screen_struct;
extern Screen dynwatch_manage_struct;
extern const Screen beaver_struct;
extern const Screen colroot_struct;
extern const Screen triggers_struct;
extern const Screen colmisc_struct;