//functions
extern void setFlag(int flagIndex, int value, char flagType);
extern int checkFlag(int flagIndex, char flagType);
extern void* dk_malloc(int size);
extern void free(void* mallocPtr);
extern void playSound(short soundIndex, int unk0, int unk1, int unk2, int unk3, int unk4);
extern void initiateTransition(int map, int exit);
extern int* getFlagBlockAddress(char flagType);
extern int isAddressActor(void* address);
extern int getTimestamp();
extern void dmaFileTransfer(int romStart, int romEnd, int* ramStart);
extern void deleteActor(void* actor);
extern int spawnActor(int actorID, int actorBehaviour);
extern void spawnTextOverlay(int style, int x, int y, char* string, int timer1, int timer2, unsigned char effect, unsigned char speed);
extern void dk_sqrt(double __x);
extern void dk_strFormat(char* destination, char* source, ...);
extern void dk_multiply(double val1, double val2, int unk1, int unk2);
extern double convertTimestamp(double unk0, double unk1, unsigned int unk2, unsigned int unk3);
extern void resetMap();
extern void prepKongColoring();
extern void callFunc(int* addr);
extern int getTimestampDiff(unsigned int major, unsigned int minor);
extern void patchHook(unsigned int hook_rdram_location, int offset_in_hook_list, char hook_byte_size);
extern void* dk_memcpy(void* _dest, void* _src, int size);
extern void getTimestampDiffInTicks(unsigned int major, unsigned int minor);
extern int timestampDiffToMilliseconds(unsigned int major, unsigned int minor);
extern int ReadFile(int DataIndex, char KongIndex, int levelIndex, int FileIndex);
extern void SaveToFile(int DataIndex, char KongIndex, int levelIndex, int FileIndex);
extern void SaveGame();

//vanilla data

extern float TransitionSpeed;
extern char CutsceneWillPlay;
extern char KRoolRound;
extern KongBase MovesBase[6];
extern int PlayerOneColor;
extern char Mode;
extern char TBVoidByte;
extern int CurrentMap;
extern int DestMap;
extern int DestExit;
extern char StorySkip;
extern char HelmTimerShown;
extern char TempFlagBlock[0x10];
extern char InSubmap;
extern short ParentMap;
extern char ParentExit;
extern char HelmTimerPaused;
extern int LagBoost;
extern int FrameLag;
extern int FrameReal;
extern int RNG;
extern char BetaNinRWSkip;
extern char LogosDestMap;
extern char LogosDestMode;
extern char Gamemode;
extern int* ObjectModel2Pointer;
extern int ObjectModel2Timer;
extern int ObjectModel2Count;
extern int ObjectModel2Count_Dupe;
extern short CutsceneIndex;
extern char CutsceneActive;
extern cutsceneType* CutsceneTypePointer;
extern short PreviousCameraState;
extern short CurrentCameraState;
extern short CameraStateChangeTimer;
extern int* AutowalkPointer;
extern char IsAutowalking;
extern WarpInfo PositionWarpInfo;
extern short PositionWarpBitfield;
extern float PositionFloatWarps[3];
extern unsigned short PositionFacingAngle;
extern char ChimpyCam;
extern char ScreenRatio;
extern int* CurrentActorPointer;
extern char LoadedActorCount;
extern int* SpawnerArray;
extern short SpawnerCount;
extern RGB MenuSkyTopRGB;
extern RGB MenuSkyRGB;
extern int* ActorArray[];
extern short ActorCount;
extern short ButtonsEnabledBitfield;
extern char JoystickEnabledX;
extern char JoystickEnabledY;
extern char MapState;
extern Controller ControllerInput;
extern Controller NewlyPressedControllerInput;
extern playerData* Player;
extern SwapObjectData* SwapObject;
extern char Character;
extern int* Camera;
extern char ISGActive;
extern unsigned int ISGTimestampMajor;
extern unsigned int ISGTimestampMinor;
extern char ISGPreviousFadeout;
extern unsigned int CurrentTimestampMajor;
extern unsigned int CurrentTimestampMinor;
extern ISGFadeoutData ISGFadeoutArray[];
extern InventoryBase CollectableBase;
extern char ModelTwoTouchCount;
extern short ModelTwoTouchArray[4];
extern char TransitionProgress;
extern Controller BackgroundHeldInput;
extern unsigned int PauseTimestampMajor;
extern unsigned int PauseTimestampMinor;
extern unsigned int HelmStartTimestampMajor;
extern unsigned int HelmStartTimestampMinor;
extern int HelmStartTime;
extern short p1PressedButtons;
extern short p1HeldButtons;

//hack data
extern int TestVariable;
extern savedSettings StoredSettings;

extern TextOverlay* ActiveTools_Error;
extern TextOverlay* ActiveToolsMenu[];
extern PosState PositionSavestate;
extern char InBadMap;
extern char MenuSavestateAction;
extern char WatchIndex[4];
extern char SniperOn;
extern char SlamLevel;
extern float AverageLag;
extern int ISGTimer;
extern char LagDocumentationIndex;
extern short StoredLag;
extern TimerInfo TimerData;
extern char StoredRound;
extern char DisablePositionButtons;
extern char DisableTagAnywhere;
extern int FrameAdvanceStart;
extern char DisableStartupSkip;
extern char DisableForcedStorySkip;
extern int* SandstormAddress;
extern char AutoPhaseStateOn;
extern GiantKoshaData* GiantKoshaTimerAddress;
extern short GiantKoshaTimerValue;
extern char MenuShortcutButtonsOff;
extern char FrameAdvancing;
extern char ArtificialPauseOn;
extern char InfiniteHealthCheatOn;
extern char LToLevitateOn;
extern ActiveMenuData ActiveMenu;
extern int NewMenu_ErrorStart;
extern char FocusedSavestate;
extern char AutoMoonkickOn;
extern char EnemySpawnOff;
extern TextOverlay* WatchActor[4];
extern PhaseCheckerData PhaseChecker;
extern char WatchTextSpace[4][0x30];
extern customFlagData CustomFlag;
extern char ISGStage;
extern char IsPauseMenuOpen;
extern short PreviousFrameButtons;
extern short UndoFlag_EncodedFlag;
extern char UndoFlag_OutputBool;
extern char UndoFlag_FlagType;
extern char UndoFlag_FlagStored;
extern char LastLoadStateAction;
extern char PauseMenuMusicSetting;
extern char ClosingMenu;
extern char HasNeutralStickInput;
extern char TouchingGB;
extern char IsSuperspeedOn;
extern char LToCancelCSOn;
extern char LToToggleTBOn;
extern char LToEndGameOn;
extern unsigned int TempTimestampStorageMajor;
extern unsigned int TempTimestampStorageMinor;
extern TextOverlay* HackTitle;
extern TextOverlay* HackVersion;
extern char AddedCorruptionActorCount;
extern int* graphicalOverlaySpace[32][3];
extern char Precision;
extern char LoadedHooks;
extern char PreviousLagArray[16];
extern char InputDisplayIndex;
extern char RAMDisplayOpen;
extern char LoadVarsOnMapLoad;
extern char ShowSavePrompts;
extern unsigned char SavePromptTimer;
extern TextOverlay* SavePromptActor;
extern char SavePromptIsSaving;