//functions
extern void setFlag(int flagIndex, int value, char flagType);
extern int checkFlag(int flagIndex, char flagType);
extern void* dk_malloc(int size);
extern void free(void* mallocPtr);
extern void playSound(short soundIndex, int unk0, int unk1, int unk2, int unk3, int unk4);
extern void initiateTransition(int map, int exit);
extern int getFlagBlockAddress(char flagType);
extern int isAddressActor(void* address);
extern void getTimestamp();
extern void dmaFileTransfer(int romStart, int romEnd, int* ramStart);
extern void deleteActor(int* actor);
extern int spawnActor(int actorID);
extern void spawnTextOverlay(int style, int x, int y, char* string, int timer1, int timer2, unsigned char effect, unsigned char speed);
extern void dk_sqrt(double __x);
extern void dk_strFormat(char* destination, char* source, ...);
extern void dk_multiply(double val1, double val2);
extern double convertTimestamp(double unk0, double unk1, unsigned int unk2, unsigned int unk3);
extern void resetMap();
extern void prepKongColoring();
extern void callFunc(int* addr);

//vanilla data
extern float TransitionSpeed;
extern char CutsceneWillPlay;
extern char KRoolRound;
extern KongBase MovesBase[5];
extern int PlayerOneColor;
extern char Mode;
extern char TBVoidByte;
extern int CurrentMap;
extern int DestMap;
extern int DestExit;
extern char StorySkip;
extern char HelmTimerShown;
extern char TempFlagBlock[0x10];
extern char InSubmap;
extern short ParentMap;
extern char ParentExit;
extern char HelmTimerPaused;
extern int LagBoost;
extern int FrameLag;
extern int FrameReal;
extern int RNG;
extern char BetaNinRWSkip;
extern char Gamemode;
extern int* ObjectModel2Pointer;
extern int ObjectModel2Timer;
extern int ObjectModel2Count;
extern int ObjectModel2Count_Dupe;
extern short CutsceneIndex;
extern char CutsceneActive;
extern int* CutsceneTypePointer;
extern short PreviousCameraState;
extern short CurrentCameraState;
extern short CameraStateChangeTimer;
extern int* AutowalkPointer;
extern char IsAutowalking;
extern short PositionWarpInfo[3];
extern short PositionWarpBitfield;
extern float PositionFloatWarps[3];
extern char ChimpyCam;
extern char ScreenRatio;
extern int* CurrentActorPointer;
extern char LoadedActorCount;
extern int* SpawnerArray;
extern short SpawnerCount;
extern RGB MenuSkyTopRGB;
extern RGB MenuSkyRGB;
extern int* ActorArray[];
extern short ActorCount;
extern short ButtonsEnabledBitfield;
extern char JoystickEnabledX;
extern char JoystickEnabledY;
extern char MapState;
extern Controller ControllerInput;
extern Controller NewlyPressedControllerInput;
extern playerData* Player;
extern int* SwapObject;
extern char Character;
extern int* Camera;
extern char ISGActive;
extern double ISGTimestamp;
extern char ISGPreviousFadeout;
extern double CurrentTimestamp;
extern double ISGFadeoutArray[];
extern InventoryBase CollectableBase;
extern char ModelTwoTouchCount;
extern short ModelTwoTouchArray[];
extern char TransitionProgress;
extern Controller BackgroundHeldInput;
extern double PauseTimestamp;
extern double HelmStartTimestamp;

//hack data
extern int TestVariable;

extern TextOverlay* ActiveTools_Error;
extern TextOverlay* ActiveToolsMenu[];
extern PosState PositionSavestate;
extern char InBadMap;
extern char MenuSavestateAction;
extern char WatchIndex;
extern char SniperOn;
extern char SlamLevel;
extern int CumulativeLag;
extern int ISGTimer;
extern int StoredLag;
extern TimerInfo TimerData;
extern char StoredRound;
extern char DisablePositionButtons;
extern char DisableTagAnywhere;
extern int FrameAdvanceStart;
extern char DisableStartupSkip;
extern char DisableForcedStorySkip;
extern int* SandstormAddress;
extern char AutoPhaseStateOn;
extern int* GiantKoshaTimerAddress;
extern short GiantKoshaTimerValue;
extern char MenuShortcutButtonsOff;
extern char FrameAdvancing;
extern char ArtificialPauseOn;
extern char InfiniteHealthCheatOn;
extern char LToLevitateOn;
extern ActiveMenuData ActiveMenu;
extern int NewMenu_ErrorStart;
extern char FocusedSavestate;
extern char AutoMoonkickOn;
extern char EnemySpawnOff;
extern int* WatchActor;
extern PhaseCheckerData PhaseChecker;
extern char WatchTextSpace[0x30];
extern short CustomFlagByte;
extern char CustomFlagBit;
extern char CustomFlagType;
extern char CustomFlagSet;
extern char ISGStage;
extern char IsPauseMenuOpen;
extern short PreviousFrameButtons;
extern short UndoFlag_EncodedFlag;
extern char UndoFlag_OutputBool;
extern char UndoFlag_FlagType;
extern char UndoFlag_FlagStored;
extern char LastLoadStateAction;
extern char PauseMenuMusicSetting;
extern char ClosingMenu;
extern char HasNeutralStickInput;
extern char TouchingGB;
extern char IsSuperspeedOn;
extern char LToCancelCSOn;
extern char LToToggleTBOn;
extern char LToEndGameOn;
extern double TempTimestampStorage;
extern TextOverlay* HackTitle;
extern TextOverlay* HackVersion;
extern char AddedCorruptionActorCount;
extern int* graphicalOverlaySpace[32][3];